name: news_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^9.0.0
  equatable: ^2.0.3
  http: ^1.2.1
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.15
  intl: ^0.20.2
  cached_network_image: ^3.2.1
  flutter_native_splash: ^2.2.7
  flutter_launcher_icons: ^0.14.3
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_native_splash:
  color: "464646"
  image: assets/images/bird.png

flutter_icons:
  android: 'ic_launcher'
  ios: true
  image_path: "assets/images/bird.jpg"

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Roboto_Slab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 500